/* Insert Genres */
INSERT [dbo].[GENRE] ([GENRE_ID], [VERSION], [NAME], [DESCRIPTION]) VALUES (N'3c5f26af-2c54-4267-8ed2-a58200b2f8a0', 1, N'Rock', N'Rock and Roll is a form of rock music developed in the 1950s and 1960s. Rock music combines many kinds of music from the United States, such as country music, folk music, church music, work songs, blues and jazz.')
INSERT [dbo].[GENRE] ([GENRE_ID], [VERSION], [NAME], [DESCRIPTION]) VALUES (N'a67cb105-918d-47b2-9731-a58200b4e63c', 1, N'Metal', N'Heavy Metal is a loud, aggressive style of Rock music. The bands who play heavy-metal music usually have one or two guitars, a bass guitar and drums. In some bands, electronic keyboards, organs, or other instruments are used. Heavy metal songs are loud and powerful-sounding, and have strong rhythms that are repeated. There are many different types of Heavy Metal, some of which are described below. Heavy metal bands sometimes dress in jeans, leather jackets, and leather boots, and have long hair. Heavy metal bands sometimes behave in a dramatic way when they play their instruments or sing. However, many heavy metal bands do not like to do this.')
INSERT [dbo].[GENRE] ([GENRE_ID], [VERSION], [NAME], [DESCRIPTION]) VALUES (N'6bdb9f3f-e099-4220-a8b9-a58200b4f5ea', 1, N'Alternative', N'Alternative rock is a type of rock music that became popular in the 1980s and became widely popular in the 1990s. Alternative rock is made up of various subgenres that have come out of the indie music scene since the 1980s, such as grunge, indie rock, Britpop, thic rock, and indie pop. These genres are sorted by their collective types of punk, which laid the groundwork for alternative music in the 1970s.')
INSERT [dbo].[GENRE] ([GENRE_ID], [VERSION], [NAME], [DESCRIPTION]) VALUES (N'56fed09a-7533-403c-af60-a58200b52446', 1, N'Disco', N'Disco is a style of pop music that was popular in the mid-1970s. Disco music has a strong beat that people can dance to. People usually dance to disco music at bars called disco clubs. The word "disco" is also used to refer to the style of dancing that people do to disco music, or to the style of clothes that people wear to  disco dancing. Disco was at its most popular in the United States and Europe in the 1970s and early 1980s. Disco was brought into the mainstream by the hit movie Saturday Night Fever, which was released in 1977. This movie, which starred John Travolta, showed people doing disco dancing. Many radio stations played disco in the late 1970s.')
INSERT [dbo].[GENRE] ([GENRE_ID], [VERSION], [NAME], [DESCRIPTION]) VALUES (N'982327c0-a04c-4be2-87b6-a58200b52f89', 1, N'Blues', N'The blues is a form of music that started in the United States during the start of the 20th century. It was started by former African slaves from spirituals, praise songs, and chants. The first blues songs were called Delta blues. These songs came from the area near the mouth of the Mississippi River.')
INSERT [dbo].[GENRE] ([GENRE_ID], [VERSION], [NAME], [DESCRIPTION]) VALUES (N'e77ac96c-6787-49ab-a4d8-a58200b5465b', 1, N'Reggae', N'Reggae is a music genre first developed in Jamaica in the late 1960s. While sometimes used in a broader sense to refer to most types of Jamaican music, the term reggae more properly denotes a particular music style that originated following on the development of ska and rocksteady.')
INSERT [dbo].[GENRE] ([GENRE_ID], [VERSION], [NAME], [DESCRIPTION]) VALUES (N'30771ab4-3c76-4874-93e5-a58200b54f21', 1, N'Pop', N'Pop music is a music genre that developed from the mid-1950s as a softer alternative to rock ''n'' roll and later to rock music. It has a focus on commercial recording, often oriented towards a youth market, usually through the medium of relatively short and simple love songs. While these basic elements of the genre have remained fairly constant, pop music has absorbed influences from most other forms of popular music, particularly borrowing from the development of rock music, and utilizing key technological innovations to produce new variations on existing themes.')

/* Insert Artists */
INSERT [dbo].[ARTIST] ([ARTIST_ID], [VERSION], [NAME]) VALUES (N'41fa797f-589f-47dd-8b9e-a58200dae6a0', 1, N'Motley Crue')
INSERT [dbo].[ARTIST] ([ARTIST_ID], [VERSION], [NAME]) VALUES (N'85e8907c-7ab9-4bd5-bc16-a58200daf3d8', 1, N'Motorhead')
INSERT [dbo].[ARTIST] ([ARTIST_ID], [VERSION], [NAME]) VALUES (N'b1e8aedf-0501-4ac0-84bb-a58200db78a3', 1, N'Garth Brooks')

/* Insert Albums */
INSERT [dbo].[ALBUM] ([ALBUM_ID], [VERSION], [GENRE_ID], [ARTIST_ID], [TITLE], [DESCRIPTION], [PRICE], [ALBUM_ART_URL]) VALUES (N'd20995d7-6c99-4373-bc4f-a58200ef113f', 1, N'a67cb105-918d-47b2-9731-a58200b4e63c', N'85e8907c-7ab9-4bd5-bc16-a58200daf3d8', N'Ace of Spades', N'<strong>Ace of Spades</strong> is the fourth album by the British heavy metal band Motörhead. Released on 8 November 1980, it peaked at No. 4 on the UK album charts and reached Gold status by March 1981. It was preceded by the release of the title track as a single on 27 October, which peaked in the UK singles chart at No. 15 in early November. It was the band''s debut release in North America, with Mercury Records handling distribution in the region.', CAST(8.3900 AS Decimal(19, 4)), N'/Content/Images/Products/motorhead_lg_.jpg')
INSERT [dbo].[ALBUM] ([ALBUM_ID], [VERSION], [GENRE_ID], [ARTIST_ID], [TITLE], [DESCRIPTION], [PRICE], [ALBUM_ART_URL]) VALUES (N'cb880bb8-51d2-4215-b6d5-a58200f4f58f', 1, N'a67cb105-918d-47b2-9731-a58200b4e63c', N'41fa797f-589f-47dd-8b9e-a58200dae6a0', N'Dr. Feelgood', N'<strong>Dr. Feelgood</strong> is the fifth studio album by the American heavy metal band Mötley Crüe, released on September 1, 1989. Dr. Feelgood topped the Billboard 200 chart and was the first album Mötley Crüe recorded after their quest for sobriety and rehabilitation in 1989. In addition to being Mötley Crüe''s best selling album, it is highly regarded by music critics and fans as the band''s best studio album.', CAST(7.9900 AS Decimal(19, 4)), N'/Content/Images/Products/motleycrue_lg_.png')

/* Insert Sequence Control */
INSERT [dbo].[SEQUENCE_CONTROL] ([SEQUENCE_CONTROL_ID], [VERSION], [LAST_SEQUENCE], [SEQUENCE_FORMAT], [INCREMENT_BY], [ZERO_PAD_TO_DIGITS]) 
VALUES ('SalesOrder', 1, 1472, 'SO-[#]', 1, 9)